### ISSUE TITLE
.dmg cannot be mounted on Mac OS (before Sierra)

### ISSUE THREAD

**Issue by CD3XT3RW4RD** [AresValley/Artemis#17]
When downloading .dmg installer, it cannot be mounted on certain systems, with error "no mountable file system". I assume problem is that .dmg was created in APFS filesystem, which is not supported OS versions older than Sierra. Can you pls generate .dmg not in APFS?

**Comment by AresValley** [comment]
From the version 3.2.1 we have an experimental legacy release for macOS: https://drive.google.com/open?id=1GEw4c8LS6nEZOPoSGW7nNCsFUz614mzm
Let us know if it works!

**Comment by CD3XT3RW4RD** [comment]
Quickly tested just the mount and it went fine even on my medieval El Capitan :)
Will test functionality in the evening.

**Comment by AresValley** [comment]
Excellent, you are welcome! I'll add the legacy version to the main download page
