### ISSUE TITLE
crash on startup on MacOS running from disk image

### ISSUE THREAD

**Issue by davepacheco** [AresValley/Artemis#25]
I just downloaded the DMG from the web site, opened it in Finder, and opened the "Artemis" app there.  (MacOS didn't want to open it because it wasn't signed, but I overrode this.)  The app started to open, but immediately was gone.  I'm not sure if it crashed or exited.  This is reproducible.  When I move the file from the DMG to the "Applications" folder, it opened up fine.

This is on MacOS Catalina 10.15.7.

**Comment by AresValley** [comment]
v4 version is rolling out these days
