### ISSUE TITLE
Missing Manual

### ISSUE THREAD

**Issue by ejboettcher** [AresValley/Artemis#36]
This looks like a neat program.  But I could not figure out how get it work with my USB SDR.  
Is there a manual that explains how to get Artemis to "see" my SDR and then how I can use Artemis to decode / ID signal.

Thank you
Evelyn

**Comment by papadeltasierra** [comment]
Seconded.  I was hoping to import a large capture that I have but no idea whether this is even possible!

**Comment by AresValley** [comment]
Artemis usage is pretty straightforward but, just in case, the complete documentation can be found on the main GitHub page. Since the documentation has the same importance as the program itself, if a feature can't be found it means that the program is not designed to do such operations

**Comment by papadeltasierra** [comment]
I think you are assuming that all users are experienced at using such programs or perhaps I have just not found the documentation?  I installed it fine (this is documented) and I understand the database format (which is documented) but I have found absolutely no instructions at all on how to actually use it.  I am guessing it can only use live data somehow (from where? which devices? which of the many RTL-SDR drivers does Artemis prefer?) and then I can somehow analyse what I find?

**Comment by AresValley** [comment]
> OK, let me see if I have this clear then. How I might use Artemis would be:
> 
> 1. Capture a signal using something like airspy/sdrsharp
> 2. Look at what I captured and in another window,  browse the database in Artemis until I find something similar.
> 
> Presumably the filters help me filter by frequency etc to try and narrow down?

Yes, that's right. Now, the full documentation of Artemis 4 can be found [HERE](https://aresvalley.github.io/Artemis). The new version is rolling out these days and the docs are still work in progress but the main part is already there with one example of real usage. I close the issue due to the new documentation released.

**Comment by AresValley** [comment]
if something is not clear in the manual feel free to open an issue or even contribute to the manual ;)
