### ISSUE TITLE
Application crash when trying to set filters

### ISSUE THREAD

**Issue by Tricopetaurus** [AresValley/Artemis#37]
- Ubuntu 22.04
- Most recent commit off master (b41ad0e8f2c39b131529994c56fba9a96bef891d)
- Fresh install, Python3.10.5

***

First time trying out this application, so far seems like my install's brittle?

Goal: Find some signals that are PSK modulated.
- Launch script with `python ./artemis.py`
- Select "Filters" at the top
- Select "Modulation"
- Type "PSK" in filter box
- Double-click PSK
- Crash
```
pygame 2.1.3 (SDL 2.0.22, Python 3.10.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/XXXXXX/git/Artemis/src/filters.py", line 629, in _remove_if_unselected_modulation
    self._show_matching_modulations(self.search_bar_modulation.text())
AttributeError: 'ModulationFilter' object has no attribute 'search_bar_modulation'
[1]    64127 IOT instruction (core dumped)  python ./artemis.py
```

**Comment by AresValley** [comment]
Artemis 4 is rolling out these days. The 2nd RC is available here: [https://github.com/AresValley/Artemis/releases](https://github.com/AresValley/Artemis/releases).
