### ISSUE TITLE
Make list navigable with cursor keys

### ISSUE THREAD

**Issue by fotografm** [AresValley/Artemis#50]
Instead of using mouse/trackpad to select then click on a signal sample from the list, it would be helpful if the selection could be made with keyboard up/down cursor keys.

**Comment by AresValley** [comment]
Thanks for the suggestion! The feature has been implemented, and the signal list can now be navigated with up/down keys. This is extended to the entire program: we can navigate through the commands using the tab and spacebar to select something or press buttons (this is the default behavior).
This change will be available for the next release.
