### ISSUE TITLE
I can't find basic signals like adsb

### ISSUE THREAD

**Issue by poetajuan** [AresValley/Artemis#52]
Very good application, congratulations.
I don't know why the basic frequency of the ADSB is not set, there is a similar one but it does not correspond in frequency and name. The correct one is Automatic Dependent Surveillance-Transmission (ADS-B) 978MHz - 1,090MHz.

**Comment by AresValley** [comment]
Thanks @poetajuan! I can't find the problem you described. This is what I see by selecting ADS-B
![Screenshot 2024-06-15 134428](https://github.com/AresValley/Artemis/assets/47104118/127fe864-ba17-465b-99d6-c7981ae3dcac)
and this is exactly corresponding to sigid wiki (https://www.sigidwiki.com/wiki/Automatic_Dependent_Surveillance-Broadcast_(ADS-B)). Maybe I misunderstood your question. Can you give me more details?

**Comment by AresValley** [comment]
Closing for lack of feedback and because the alleged problem, with the given information, is not reproducible.
Feel free to open the issue again with more details
